use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum Manufacturer {
    AmGeneral,
    Agrale,
    AlfaRomeo,
    AstonMartin,
    Audi,
    Bmw,
    Bentley,
    Cadillac,
    Chery,
    Chevrolet,
    Chrysler,
    Citroen,
    CrossLander,
    Ds,
    Daewoo,
    Daihatsu,
    Dodge,
    Effa,
    Ferrari,
    Fiat,
    Ford,
    Gmc,
    Geely,
    Gurgel,
    Hafei,
    Haima,
    Honda,
    Hummer,
    Hyundai,
    Infiniti,
    Iveco,
    Jac,
    Jpx,
    Jaguar,
    Jeep,
    Kia,
    Lada,
    Lamborghini,
    LandRover,
    Lexus,
    Lifan,
    Lotus,
    Mg,
    Mini,
    Mahindra,
    Maserati,
    Mazda,
    McLaren,
    MercedesBenz,
    Mitsubishi,
    Nissan,
    Puma,
    Peugeot,
    Porsche,
    Renault,
    RollsRoyce,
    Seat,
    Santana,
    Shineray,
    Smart,
    Ssangyong,
    Subaru,
    Suzuki,
    Tac,
    Toyota,
    Troller,
    Volkswagen,
    Volvo,
    Voyage,
    ApcMotorCompany,
    Ajp,
    Ajs,
    Arc,
    Arch,
    Aspt,
    Adly,
    Aermacchi,
    Alcyon,
    Alta,
    Ambassador,
    AmericanIronhorse,
    AmericanLifan,
    Apollo,
    Aprilia,
    ArcticCat,
    Ariane,
    Ariel,
    ArlenNess,
    Armor,
    Armstrong,
    Artisan,
    Bmc,
    Bms,
    Bsa,
    Bts,
    Bajaj,
    Baotian,
    Barossa,
    Bashan,
    Battistinis,
    Beeline,
    Benelli,
    Beta,
    Better,
    Bianchi,
    BigBearChoppers,
    BigDogMotorcycles,
    Bimota,
    Bintelli,
    Blata,
    Boom,
    Borile,
    BossHoss,
    Bourget,
    Bown,
    Boxer,
    Brammo,
    Branson,
    Bridgestone,
    Brixton,
    BroughSuperior,
    Buell,
    Bullit,
    Bultaco,
    Butler,
    Ccm,
    Cfmoto,
    ChRacing,
    Cpi,
    Cz,
    Cagiva,
    CaliforniaMotorcycleCompany,
    CaliforniaScooterCompany,
    Campagna,
    CanAm,
    Cannondale,
    Casal,
    Cazador,
    Champ,
    ChangJiang,
    ChicagoScooterCo,
    Chunlan,
    Cimatti,
    Citycoco,
    ClubCar,
    Cobra,
    Coleman,
    Condor,
    Confederate,
    ConquestTrikes,
    Coolster,
    Cotton,
    Cougar,
    CoventryEagle,
    Cushman,
    Dkw,
    Dot,
    Daelim,
    Daix,
    Dayang,
    DemonX,
    Derbi,
    DiBlasi,
    Diamo,
    Dichao,
    DirectBikes,
    Dnepr,
    DongFang,
    Douglas,
    Dresda,
    Ducati,
    Eton,
    EzGo,
    Ebr,
    EasyRider,
    Eclipse,
    ElectricMotion,
    Electricycle,
    Energica,
    Eped,
    Erider,
    ErikBuellRacing,
    ExcelsiorHenderson,
    Fantic,
    Feiying,
    Fenian,
    Fosti,
    FrancisBarnett,
    Garelli,
    GasGas,
    Genata,
    Generic,
    GenuineScooterCompany,
    GhezziBrian,
    Giantco,
    Gilera,
    Greeves,
    Grinnall,
    Hanway,
    HaoNuo,
    Haotian,
    HarleyDavidson,
    Harris,
    Hartford,
    HellboundSteel,
    Herald,
    Hesketh,
    Himo,
    Hisun,
    Honchin,
    Hongdu,
    Honley,
    Horex,
    Huvo,
    Huatian,
    Huoniao,
    Husaberg,
    Husqvarna,
    Hyosung,
    Isomoto,
    Izh,
    IceBear,
    Indian,
    IronEagleMotorcycle,
    Italika,
    Italjet,
    Itom,
    Jbwco,
    Jcm,
    James,
    Jawa,
    Jialing,
    Jianshe,
    Jincheng,
    Jinfeng,
    Jinlun,
    JohnDeere,
    JohnnyPag,
    Jonway,
    Jotagas,
    JuicyBike,
    Kalex,
    Ktm,
    Kangchao,
    Kawasaki,
    Kayo,
    Keeway,
    KinroadRock,
    Kymco,
    Lem,
    Lambretta,
    Lance,
    Lanying,
    Laverda,
    Lehman,
    LehmanTrikes,
    Leike,
    Levis,
    Lexmoto,
    Linhai,
    Lintex,
    Lml,
    Loncin,
    Longjia,
    Lyric,
    Mbk,
    MvAgusta,
    Mz,
    Magni,
    Maico,
    Malaguti,
    Martin,
    Masai,
    Mash,
    Matchless,
    Mavizen,
    Maxus,
    Megelli,
    Mig,
    Mikilon,
    MiniMoto,
    Mobylette,
    Modenas,
    Mondial,
    Montesa,
    Morini,
    MotoGuzzi,
    MotoMartin,
    MotoMorini,
    MotoParilla,
    Motobi,
    Motobecane,
    MotorTrike,
    MotoHispania,
    Motorini,
    Motus,
    Mutt,
    Metisse,
    Munch,
    Nsu,
    Nvt,
    Neco,
    NewHudson,
    NewImperial,
    NewMap,
    Nippi,
    Nipponia,
    Niu,
    Norton,
    Oset,
    Omega,
    Ossa,
    Pgo,
    Por,
    Pannonia,
    Panther,
    ParamountCustomCycles,
    Paton,
    PeaceSports,
    Peirspeed,
    Pembleton,
    Peripoli,
    Petronas,
    Piaggio,
    Pioneer,
    PitsterPro,
    Polaris,
    Polestar,
    Polini,
    PrecisionCycleWorks,
    Puch,
    Pulse,
    Qingqi,
    Quadro,
    Quantya,
    Raleigh,
    RedHorse,
    Regent,
    Revtech,
    Rewaco,
    Rhino,
    Rickman,
    Ridley,
    Rieju,
    Roadsmith,
    Roehr,
    Rokon,
    MotoRoma,
    Romarsh,
    Romeo,
    Rovigo,
    Roxon,
    RoyalAlloy,
    RoyalEnfield,
    Rudge,
    Rumi,
    Sfm,
    SsrMotorsports,
    Stacyc,
    Swm,
    Sym,
    Sachs,
    Sanglas,
    Sanya,
    Saxon,
    Schwinn,
    Scomadi,
    Scorpa,
    Scott,
    Secma,
    Seeley,
    Segway,
    Senke,
    Sherco,
    Siamoto,
    Silk,
    Simson,
    Sinnis,
    Skygo,
    Skyjet,
    Skyteam,
    Slam,
    Slingshot,
    Smc,
    Spirit,
    Spondon,
    StarMotorcycles,
    Starway,
    Stomp,
    SuckerPunchSallys,
    Sukida,
    Sumo,
    Sunbeam,
    SuperSoco,
    Superbyke,
    Swift,
    Tgb,
    TaizhouZhongneng,
    Tamoretti,
    TaoMotor,
    TaoTao,
    Terrot,
    ThoroughbredMotorsports,
    Thumpstar,
    ThunderMountain,
    Titan,
    Tmec,
    Tomos,
    Tor,
    Track,
    Trailmaster,
    Triton,
    Triumph,
    Ubco,
    Um,
    Ural,
    Urban,
    Vor,
    Vanderhall,
    Vectrix,
    Velocette,
    Vento,
    Venture,
    Vertemati,
    Vertigo,
    Vespa,
    Victoria,
    Victory,
    Vincent,
    Vitacci,
    Voxan,
    Vulcan,
    Vyrus,
    Velosolex,
    WkBikes,
    Wangye,
    WildWest,
    WolfBrandScooters,
    Wuyang,
    Xgjao,
    Xispa,
    XtremeMotorCo,
    Ycf,
    Yamaha,
    Yamasaki,
    Yamoto,
    Yiben,
    Yuan,
    Zenardi,
    Zennco,
    Zero,
    ZeroEngineering,
    Zhejiang,
    Znen,
    Zodiac,
    Zongshen,
    Zontes,
    Tm,

    Other,
}

impl Manufacturer {
    pub fn transform(&self) -> &'static str {
        match self {
            Self::AmGeneral => "AM General",
            Self::Agrale => "Agrale",
            Self::AlfaRomeo => "Alfa Romeo",
            Self::AstonMartin => "Aston Martin",
            Self::Audi => "Audi",
            Self::Bmw => "BMW",
            Self::Bentley => "Bentley",
            Self::Cadillac => "Cadillac",
            Self::Chery => "Chery",
            Self::Chevrolet => "Chevrolet",
            Self::Chrysler => "Chrysler",
            Self::Citroen => "Citroën",
            Self::CrossLander => "Cross Lander",
            Self::Ds => "DS",
            Self::Daewoo => "Daewoo",
            Self::Daihatsu => "Daihatsu",
            Self::Dodge => "Dodge",
            Self::Effa => "Effa",
            Self::Ferrari => "Ferrari",
            Self::Fiat => "FIAT",
            Self::Ford => "Ford",
            Self::Gmc => "GMC",
            Self::Geely => "Geely",
            Self::Gurgel => "Gurgel",
            Self::Hafei => "Hafei",
            Self::Haima => "Haima",
            Self::Honda => "Honda",
            Self::Hummer => "Hummer",
            Self::Hyundai => "Hyundai",
            Self::Infiniti => "Infiniti",
            Self::Iveco => "Iveco",
            Self::Jac => "JAC",
            Self::Jpx => "JPX",
            Self::Jaguar => "Jaguar",
            Self::Jeep => "Jeep",
            Self::Kia => "Kia",
            Self::Lada => "Lada",
            Self::Lamborghini => "Lamborghini",
            Self::LandRover => "Land Rover",
            Self::Lexus => "Lexus",
            Self::Lifan => "Lifan",
            Self::Lotus => "Lotus",
            Self::Mg => "MG",
            Self::Mini => "MINI",
            Self::Mahindra => "Mahindra",
            Self::Maserati => "Maserati",
            Self::Mazda => "Mazda",
            Self::McLaren => "McLaren",
            Self::MercedesBenz => "Mercedes-Benz",
            Self::Mitsubishi => "Mitsubishi",
            Self::Nissan => "Nissan",
            Self::Puma => "PUMA",
            Self::Peugeot => "Peugeot",
            Self::Porsche => "Porsche",
            Self::Renault => "Renault",
            Self::RollsRoyce => "Rolls-Royce",
            Self::Seat => "SEAT",
            Self::Santana => "Santana",
            Self::Shineray => "Shineray",
            Self::Smart => "Smart",
            Self::Ssangyong => "Ssangyong",
            Self::Subaru => "Subaru",
            Self::Suzuki => "Suzuki",
            Self::Tac => "TAC",
            Self::Toyota => "Toyota",
            Self::Troller => "Troller",
            Self::Volkswagen => "Volkswagen",
            Self::Volvo => "Volvo",
            Self::Voyage => "Voyage",
            Self::ApcMotorCompany => "A.P.C Motor Company",
            Self::Ajp => "AJP",
            Self::Ajs => "AJS",
            Self::Arc => "ARC",
            Self::Arch => "Arch",
            Self::Aspt => "ASPT",
            Self::Adly => "Adly",
            Self::Aermacchi => "Aermacchi",
            Self::Alcyon => "Alcyon",
            Self::Alta => "Alta",
            Self::Ambassador => "Ambassador",
            Self::AmericanIronhorse => "American IronHorse",
            Self::AmericanLifan => "American Lifan",
            Self::Apollo => "Apollo",
            Self::Aprilia => "Aprilia",
            Self::ArcticCat => "Arctic Cat",
            Self::Ariane => "Ariane",
            Self::Ariel => "Ariel",
            Self::ArlenNess => "Arlen Ness",
            Self::Armor => "Armor",
            Self::Armstrong => "Armstrong",
            Self::Artisan => "Artisan",
            Self::Bmc => "BMC",
            Self::Bms => "BMS",
            Self::Bsa => "BSA",
            Self::Bts => "BTS",
            Self::Bajaj => "Bajaj",
            Self::Baotian => "Baotian",
            Self::Barossa => "Barossa",
            Self::Bashan => "Bashan",
            Self::Battistinis => "Battistinis",
            Self::Beeline => "Beeline",
            Self::Benelli => "Benelli",
            Self::Beta => "Beta",
            Self::Better => "Better",
            Self::Bianchi => "Bianchi",
            Self::BigBearChoppers => "Big Bear Choppers",
            Self::BigDogMotorcycles => "Big Dog Motorcycles",
            Self::Bimota => "Bimota",
            Self::Bintelli => "Bintelli",
            Self::Blata => "Blata",
            Self::Boom => "Boom",
            Self::Borile => "Borile",
            Self::BossHoss => "Boss Hoss",
            Self::Bourget => "Bourget",
            Self::Bown => "Bown",
            Self::Boxer => "Boxer",
            Self::Brammo => "Brammo",
            Self::Branson => "Branson",
            Self::Bridgestone => "Bridgestone",
            Self::Brixton => "Brixton",
            Self::BroughSuperior => "Brough Superior",
            Self::Buell => "Buell",
            Self::Bullit => "Bullit",
            Self::Bultaco => "Bultaco",
            Self::Butler => "Butler",
            Self::Ccm => "CCM",
            Self::Cfmoto => "CFMOTO",
            Self::ChRacing => "CH Racing",
            Self::Cpi => "CPI",
            Self::Cz => "CZ",
            Self::Cagiva => "Cagiva",
            Self::CaliforniaMotorcycleCompany => "California Motorcycle Company",
            Self::CaliforniaScooterCompany => "California Scooter Company",
            Self::Campagna => "Campagna",
            Self::CanAm => "Can-Am",
            Self::Cannondale => "Cannondale",
            Self::Casal => "Casal",
            Self::Cazador => "Cazador",
            Self::Champ => "Champ",
            Self::ChangJiang => "Chang Jiang",
            Self::ChicagoScooterCo => "Chicago Scooter Co",
            Self::Chunlan => "Chunlan",
            Self::Cimatti => "Cimatti",
            Self::Citycoco => "Citycoco",
            Self::ClubCar => "Club Car",
            Self::Cobra => "Cobra",
            Self::Coleman => "Coleman",
            Self::Condor => "Condor",
            Self::Confederate => "Confederate",
            Self::ConquestTrikes => "Conquest Trikes",
            Self::Coolster => "Coolster",
            Self::Cotton => "Cotton",
            Self::Cougar => "Cougar",
            Self::CoventryEagle => "Coventry Eagle",
            Self::Cushman => "Cushman",
            Self::Dkw => "DKW",
            Self::Dot => "Dot",
            Self::Daelim => "Daelim",
            Self::Daix => "Daix",
            Self::Dayang => "Dayang",
            Self::DemonX => "Demon X",
            Self::Derbi => "Derbi",
            Self::DiBlasi => "Di Blasi",
            Self::Diamo => "Diamo",
            Self::Dichao => "Dichao",
            Self::DirectBikes => "Direct Bikes",
            Self::Dnepr => "Dnepr",
            Self::DongFang => "Dong Fang",
            Self::Douglas => "Douglas",
            Self::Dresda => "Dresda",
            Self::Ducati => "Ducati",
            Self::Eton => "E-TON",
            Self::EzGo => "E-Z-Go",
            Self::Ebr => "EBR",
            Self::EasyRider => "Easy-Rider",
            Self::Eclipse => "Eclipse",
            Self::ElectricMotion => "Electric Motion",
            Self::Electricycle => "Electricycle",
            Self::Energica => "Energica",
            Self::Eped => "Eped",
            Self::Erider => "Erider",
            Self::ErikBuellRacing => "Erik Buell Racing",
            Self::ExcelsiorHenderson => "Excelsior Henderson",
            Self::Fantic => "Fantic",
            Self::Feiying => "Feiying",
            Self::Fenian => "Fenian",
            Self::Fosti => "Fosti",
            Self::FrancisBarnett => "Francis-Barnett",
            Self::Garelli => "Garelli",
            Self::GasGas => "Gas Gas",
            Self::Genata => "Genata",
            Self::Generic => "Generic",
            Self::GenuineScooterCompany => "Genuine Scooter Company",
            Self::GhezziBrian => "Ghezzi-Brian",
            Self::Giantco => "Giantco",
            Self::Gilera => "Gilera",
            Self::Greeves => "Greeves",
            Self::Grinnall => "Grinnall",
            Self::Hanway => "Hanway",
            Self::HaoNuo => "Hao Nuo",
            Self::Haotian => "Haotian",
            Self::HarleyDavidson => "Harley-Davidson",
            Self::Harris => "Harris",
            Self::Hartford => "Hartford",
            Self::HellboundSteel => "Hellbound Steel",
            Self::Herald => "Herald",
            Self::Hesketh => "Hesketh",
            Self::Himo => "Himo",
            Self::Hisun => "Hisun",
            Self::Honchin => "Honchin",
            Self::Hongdu => "Hongdu",
            Self::Honley => "Honley",
            Self::Horex => "Horex",
            Self::Huvo => "Huvo",
            Self::Huatian => "Huatian",
            Self::Huoniao => "Huoniao",
            Self::Husaberg => "Husaberg",
            Self::Husqvarna => "Husqvarna",
            Self::Hyosung => "Hyosung",
            Self::Isomoto => "Isomoto",
            Self::Izh => "IZH",
            Self::IceBear => "Ice Bear",
            Self::Indian => "Indian",
            Self::IronEagleMotorcycle => "Iron Eagle Motorcycle",
            Self::Italika => "Italika",
            Self::Italjet => "Italjet",
            Self::Itom => "Itom",
            Self::Jbwco => "Jbwco",
            Self::Jcm => "JCM",
            Self::James => "James",
            Self::Jawa => "Jawa",
            Self::Jialing => "Jialing",
            Self::Jianshe => "Jianshe",
            Self::Jincheng => "Jincheng",
            Self::Jinfeng => "Jinfeng",
            Self::Jinlun => "Jinlun",
            Self::JohnDeere => "John Deere",
            Self::JohnnyPag => "Johnny Pag",
            Self::Jonway => "Jonway",
            Self::Jotagas => "Jotagas",
            Self::JuicyBike => "Juicy Bike",
            Self::Kalex => "Kalex",
            Self::Ktm => "KTM",
            Self::Kangchao => "Kangchao",
            Self::Kawasaki => "Kawasaki",
            Self::Kayo => "Kayo",
            Self::Keeway => "Keeway",
            Self::KinroadRock => "Kinroad-Rock",
            Self::Kymco => "Kymco",
            Self::Lem => "Lem",
            Self::Lambretta => "Lambretta",
            Self::Lance => "Lance",
            Self::Lanying => "Lanying",
            Self::Laverda => "Laverda",
            Self::Lehman => "Lehman",
            Self::LehmanTrikes => "Lehman Trikes",
            Self::Leike => "Leike",
            Self::Levis => "Levis",
            Self::Lexmoto => "Lexmoto",
            Self::Linhai => "Linhai",
            Self::Lintex => "Lintex",
            Self::Lml => "LML",
            Self::Loncin => "Loncin",
            Self::Longjia => "Longjia",
            Self::Lyric => "Lyric",
            Self::Mbk => "MBK",
            Self::MvAgusta => "MV Agusta",
            Self::Mz => "MZ",
            Self::Magni => "Magni",
            Self::Maico => "Maico",
            Self::Malaguti => "Malaguti",
            Self::Martin => "Martin",
            Self::Masai => "Masai",
            Self::Mash => "Mash",
            Self::Matchless => "Matchless",
            Self::Mavizen => "Mavizen",
            Self::Maxus => "Maxus",
            Self::Megelli => "Megelli",
            Self::Mig => "Mig",
            Self::Mikilon => "Mikilon",
            Self::MiniMoto => "Mini Moto",
            Self::Mobylette => "Mobylette",
            Self::Modenas => "Modenas",
            Self::Mondial => "Mondial",
            Self::Montesa => "Montesa",
            Self::Morini => "Morini",
            Self::MotoGuzzi => "Moto Guzzi",
            Self::MotoMartin => "Moto-Martin",
            Self::MotoMorini => "Moto Morini",
            Self::MotoParilla => "Moto-Parilla",
            Self::Motobi => "Motobi",
            Self::Motobecane => "Motobecane",
            Self::MotorTrike => "Motor Trike",
            Self::MotoHispania => "Moto-Hispania",
            Self::Motorini => "Motorini",
            Self::Motus => "Motus",
            Self::Mutt => "Mutt",
            Self::Metisse => "Metisse",
            Self::Munch => "Munch",
            Self::Nsu => "NSU",
            Self::Nvt => "NVT",
            Self::Neco => "Neco",
            Self::NewHudson => "New Hudson",
            Self::NewImperial => "New Imperial",
            Self::NewMap => "New Map",
            Self::Nippi => "Nippi",
            Self::Nipponia => "Nipponia",
            Self::Niu => "NIU",
            Self::Norton => "Norton",
            Self::Oset => "Oset",
            Self::Omega => "Omega",
            Self::Ossa => "Ossa",
            Self::Pgo => "PGO",
            Self::Por => "Por",
            Self::Pannonia => "Pannonia",
            Self::Panther => "Panther",
            Self::ParamountCustomCycles => "Paramount Custom Cycles",
            Self::Paton => "Paton",
            Self::PeaceSports => "Peace Sports",
            Self::Peirspeed => "Peirspeed",
            Self::Pembleton => "Pembleton",
            Self::Peripoli => "Peripoli",
            Self::Petronas => "Petronas",
            Self::Piaggio => "Piaggio",
            Self::Pioneer => "Pioneer",
            Self::PitsterPro => "Pitster Pro",
            Self::Polaris => "Polaris",
            Self::Polestar => "Polestar",
            Self::Polini => "Polini",
            Self::PrecisionCycleWorks => "Precision Cycle Works",
            Self::Puch => "Puch",
            Self::Pulse => "Pulse",
            Self::Qingqi => "Qingqi",
            Self::Quadro => "Quadro",
            Self::Quantya => "Quantya",
            Self::Raleigh => "Raleigh",
            Self::RedHorse => "Red Horse",
            Self::Regent => "Regent",
            Self::Revtech => "Revtech",
            Self::Rewaco => "Rewaco",
            Self::Rhino => "Rhino",
            Self::Rickman => "Rickman",
            Self::Ridley => "Ridley",
            Self::Rieju => "Rieju",
            Self::Roadsmith => "Roadsmith",
            Self::Roehr => "Roehr",
            Self::Rokon => "Rokon",
            Self::MotoRoma => "Moto-Roma",
            Self::Romarsh => "Romarsh",
            Self::Romeo => "Romeo",
            Self::Rovigo => "Rovigo",
            Self::Roxon => "Roxon",
            Self::RoyalAlloy => "Royal Alloy",
            Self::RoyalEnfield => "Royal Enfield",
            Self::Rudge => "Rudge",
            Self::Rumi => "Rumi",
            Self::Sfm => "SFM",
            Self::SsrMotorsports => "SSR Motorsports",
            Self::Stacyc => "Stacyc",
            Self::Swm => "SWM",
            Self::Sym => "SYM",
            Self::Sachs => "Sachs",
            Self::Sanglas => "Sanglas",
            Self::Sanya => "Sanya",
            Self::Saxon => "Saxon",
            Self::Schwinn => "Schwinn",
            Self::Scomadi => "Scomadi",
            Self::Scorpa => "Scorpa",
            Self::Scott => "Scott",
            Self::Secma => "Secma",
            Self::Seeley => "Seeley",
            Self::Segway => "Segway",
            Self::Senke => "Senke",
            Self::Sherco => "Sherco",
            Self::Siamoto => "Siamoto",
            Self::Silk => "Silk",
            Self::Simson => "Simson",
            Self::Sinnis => "Sinnis",
            Self::Skygo => "Skygo",
            Self::Skyjet => "Skyjet",
            Self::Skyteam => "Skyteam",
            Self::Slam => "Slam",
            Self::Slingshot => "Slingshot",
            Self::Smc => "Smc",
            Self::Spirit => "Spirit",
            Self::Spondon => "Spondon",
            Self::StarMotorcycles => "Star Motorcycles",
            Self::Starway => "Starway",
            Self::Stomp => "Stomp",
            Self::SuckerPunchSallys => "Sucker Punch Sallys",
            Self::Sukida => "Sukida",
            Self::Sumo => "Sumo",
            Self::Sunbeam => "Sunbeam",
            Self::SuperSoco => "Super Soco",
            Self::Superbyke => "Superbyke",
            Self::Swift => "Swift",
            Self::Tgb => "TGB",
            Self::TaizhouZhongneng => "Taizhou Zhongneng",
            Self::Tamoretti => "Tamoretti",
            Self::TaoMotor => "Tao Motor",
            Self::TaoTao => "Tao Tao",
            Self::Terrot => "Terrot",
            Self::ThoroughbredMotorsports => "Thoroughbred Motorsports",
            Self::Thumpstar => "Thumpstar",
            Self::ThunderMountain => "Thunder Mountain",
            Self::Titan => "Titan",
            Self::Tmec => "Tmec",
            Self::Tomos => "Tomos",
            Self::Tor => "TOR",
            Self::Track => "Track",
            Self::Trailmaster => "Trailmaster",
            Self::Triton => "Triton",
            Self::Triumph => "Triumph",
            Self::Ubco => "UBCO",
            Self::Um => "UM",
            Self::Ural => "Ural",
            Self::Urban => "Urban",
            Self::Vor => "Vor",
            Self::Vanderhall => "Vanderhall",
            Self::Vectrix => "Vectrix",
            Self::Velocette => "Velocette",
            Self::Vento => "Vento",
            Self::Venture => "Venture",
            Self::Vertemati => "Vertemati",
            Self::Vertigo => "Vertigo",
            Self::Vespa => "Vespa",
            Self::Victoria => "Victoria",
            Self::Victory => "Victory",
            Self::Vincent => "Vincent",
            Self::Vitacci => "Vitacci",
            Self::Voxan => "Voxan",
            Self::Vulcan => "Vulcan",
            Self::Vyrus => "Vyrus",
            Self::Velosolex => "Velosolex",
            Self::WkBikes => "WK Bikes",
            Self::Wangye => "Wangye",
            Self::WildWest => "Wild West",
            Self::WolfBrandScooters => "Wolf Brand Scooters",
            Self::Wuyang => "Wuyang",
            Self::Xgjao => "Xgjao",
            Self::Xispa => "Xispa",
            Self::XtremeMotorCo => "Xtreme Motor Co.",
            Self::Ycf => "YCF",
            Self::Yamaha => "Yamaha",
            Self::Yamasaki => "Yamasaki",
            Self::Yamoto => "Yamoto",
            Self::Yiben => "Yiben",
            Self::Yuan => "Yuan",
            Self::Zenardi => "Zenardi",
            Self::Zennco => "Zennco",
            Self::Zero => "Zero",
            Self::ZeroEngineering => "Zero Engineering",
            Self::Zhejiang => "Zhejiang",
            Self::Znen => "Znen",
            Self::Zodiac => "Zodiac",
            Self::Zongshen => "Zongshen",
            Self::Zontes => "Zontes",
            Self::Tm => "TM",
            Self::Other => "Outro",
        }
    }
}
